### PR TITLE
Update SDK to v2.13.x

### PR DESCRIPTION
**Pull request by Widcket**
### Changes

This PR updates the SDK to v2.13.x, and also updates other dependencies.

### CODE REVIEW

**Comment by poovamraj** [comment]
@Widcket for RN since there is an upgrade from 0.68 to 0.68.2

Should we consider the changes from here - https://react-native-community.github.io/upgrade-helper/?from=0.68.0&to=0.68.2

**Comment by Widcket** [comment]
Yup, I looked there and got confused, thought there was no diff for **0.68.2** –turns out that you need to update the value in the dropdown to the right for **0.68.0** to be available in the dropdown to the left.
Thanks for pointing it out, I'll update it.

Screen Shot 2022-05-13 at 19 03 02

**Comment by Widcket** [comment]
I found out that there were lots of changes from RN 0.67.4 to 0.68.0 that were not applied at all, so I went and applied all the changes in https://github.com/auth0-samples/auth0-react-native-sample/pull/63/commits/b1f9b40ab73ef5cf5f988f19006958ba8dbb88cc (minus the Flipper and new architecture ones).
See https://react-native-community.github.io/upgrade-helper/?from=0.67.4&to=0.68.2

**Review by poovamraj — APPROVED** [review]
👍 LGTM

**Pull request merged**
